default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: todoapp_rails_backend_development
  username: postgres
  password: root
  host: 127.0.0.1
  port: 5432

production:
  <<: *default